[package]
name = "mmap-rs"
version = "0.1.0"
edition = "2018"

[target.'cfg(windows)'.build-dependencies]
windows = "0.21"

[dependencies]
bitflags = "1.3"
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23"

[target.'cfg(windows)'.dependencies]
windows = "0.21"
